language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
deploy:
  provider: heroku
  api_key:
    secure: GXHpDmbKh7Qk5fb17O/ebS3kyQ+TwOOQoxhN/aT4PFe+TA13akQxDgdX4D9AtZLZI85gs9Qr8HBTwbpJ6/zQc6LgbFr22k/54RoGxxpbD2ngwY+AuBcdcDcL64MPm0Ws9oyysvGSmcVlTZPFaRpUVB16As8fRr0iVP06eWUwWjr9475NetsVpbhIHOkjqnDfTwpwmJ3sbtnSY9+qjP159W5wWsOSMKe30iFRR3/hlUhAn7mwHxDo/5BbawISXn54cVofzaCdDyiLT/qcEBbwSsLBLyl6lFMJWV9mSQpmD0JVeJNiVBc+0MOFP3p+4/Pe9W+yEJzF+lcEVWGLJgyoYRapgeAdfkh3ez+FK4MdRkwQzF5veAyR+/4Xgjiln7NXZFCT1ZyatiPW8WIhm3PK3ieFivryC8ZzywaHNqFTLwxKaqBxvTz3bsjBn0Ft3/+AcrG2EjPRRUjszEFQt+4W5yyQ0A8e23u3T+3yVxY9UcnTjOJkb9R8+aJ0evQELaKyzHrvn16GBUHNldOnx6kdy1C9lV3bFEjfNrTILsLU9zcWtN6Aj5B8vOV1uztPs15kOZYHe5oHpuVeERrDy/cWtoyJW2Aip23aAhOhs7yBsaqAm85fHJinOpZ0JAnty/kmrmKGL9W2qX6ATi5OPnmqhm8YSxkQnmhpz3yTdYnogII=

  app: test-app-covid